name: type check
on:
  pull_request:
    branches: [main, develop]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
      - name: Install package
        run: cd app && yarn install
      - name: eslint check
        run: npm run lint
